/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedScheduleRouteImport } from './routes/_authed/schedule'
import { Route as AuthedMoneyRouteImport } from './routes/_authed/money'
import { Route as AuthedClientsRouteImport } from './routes/_authed/clients'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedScheduleRoute = AuthedScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMoneyRoute = AuthedMoneyRouteImport.update({
  id: '/money',
  path: '/money',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedClientsRoute = AuthedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/clients': typeof AuthedClientsRoute
  '/money': typeof AuthedMoneyRoute
  '/schedule': typeof AuthedScheduleRoute
  '/settings': typeof AuthedSettingsRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/clients': typeof AuthedClientsRoute
  '/money': typeof AuthedMoneyRoute
  '/schedule': typeof AuthedScheduleRoute
  '/settings': typeof AuthedSettingsRoute
  '/': typeof AuthedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/clients': typeof AuthedClientsRoute
  '/_authed/money': typeof AuthedMoneyRoute
  '/_authed/schedule': typeof AuthedScheduleRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/': typeof AuthedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/clients' | '/money' | '/schedule' | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/clients' | '/money' | '/schedule' | '/settings' | '/'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/clients'
    | '/_authed/money'
    | '/_authed/schedule'
    | '/_authed/settings'
    | '/_authed/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/schedule': {
      id: '/_authed/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AuthedScheduleRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/money': {
      id: '/_authed/money'
      path: '/money'
      fullPath: '/money'
      preLoaderRoute: typeof AuthedMoneyRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/clients': {
      id: '/_authed/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthedClientsRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedClientsRoute: typeof AuthedClientsRoute
  AuthedMoneyRoute: typeof AuthedMoneyRoute
  AuthedScheduleRoute: typeof AuthedScheduleRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedClientsRoute: AuthedClientsRoute,
  AuthedMoneyRoute: AuthedMoneyRoute,
  AuthedScheduleRoute: AuthedScheduleRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedIndexRoute: AuthedIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
