/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedScheduleRouteImport } from './routes/_authed/schedule'
import { Route as AuthedSettingsIndexRouteImport } from './routes/_authed/settings/index'
import { Route as AuthedMoneyIndexRouteImport } from './routes/_authed/money/index'
import { Route as AuthedClientsIndexRouteImport } from './routes/_authed/clients/index'
import { Route as AuthedSettingsServicesRouteImport } from './routes/_authed/settings/services'
import { Route as AuthedSchedulesNewRouteImport } from './routes/_authed/schedules/new'
import { Route as AuthedPropertiesNewRouteImport } from './routes/_authed/properties/new'
import { Route as AuthedJobsNewRouteImport } from './routes/_authed/jobs/new'
import { Route as AuthedJobsJobIdRouteImport } from './routes/_authed/jobs/$jobId'
import { Route as AuthedInvoicesNewRouteImport } from './routes/_authed/invoices/new'
import { Route as AuthedInvoicesInvoiceIdRouteImport } from './routes/_authed/invoices/$invoiceId'
import { Route as AuthedClientsNewRouteImport } from './routes/_authed/clients/new'
import { Route as AuthedPropertiesPropertyIdIndexRouteImport } from './routes/_authed/properties/$propertyId.index'
import { Route as AuthedClientsClientIdIndexRouteImport } from './routes/_authed/clients/$clientId.index'
import { Route as AuthedSchedulesScheduleIdEditRouteImport } from './routes/_authed/schedules/$scheduleId.edit'
import { Route as AuthedPropertiesPropertyIdEditRouteImport } from './routes/_authed/properties/$propertyId.edit'
import { Route as AuthedClientsClientIdEditRouteImport } from './routes/_authed/clients/$clientId.edit'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedScheduleRoute = AuthedScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsIndexRoute = AuthedSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMoneyIndexRoute = AuthedMoneyIndexRouteImport.update({
  id: '/money/',
  path: '/money/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedClientsIndexRoute = AuthedClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsServicesRoute = AuthedSettingsServicesRouteImport.update({
  id: '/settings/services',
  path: '/settings/services',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSchedulesNewRoute = AuthedSchedulesNewRouteImport.update({
  id: '/schedules/new',
  path: '/schedules/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPropertiesNewRoute = AuthedPropertiesNewRouteImport.update({
  id: '/properties/new',
  path: '/properties/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedJobsNewRoute = AuthedJobsNewRouteImport.update({
  id: '/jobs/new',
  path: '/jobs/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedJobsJobIdRoute = AuthedJobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedInvoicesNewRoute = AuthedInvoicesNewRouteImport.update({
  id: '/invoices/new',
  path: '/invoices/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedInvoicesInvoiceIdRoute = AuthedInvoicesInvoiceIdRouteImport.update({
  id: '/invoices/$invoiceId',
  path: '/invoices/$invoiceId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedClientsNewRoute = AuthedClientsNewRouteImport.update({
  id: '/clients/new',
  path: '/clients/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPropertiesPropertyIdIndexRoute =
  AuthedPropertiesPropertyIdIndexRouteImport.update({
    id: '/properties/$propertyId/',
    path: '/properties/$propertyId/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedClientsClientIdIndexRoute =
  AuthedClientsClientIdIndexRouteImport.update({
    id: '/clients/$clientId/',
    path: '/clients/$clientId/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedSchedulesScheduleIdEditRoute =
  AuthedSchedulesScheduleIdEditRouteImport.update({
    id: '/schedules/$scheduleId/edit',
    path: '/schedules/$scheduleId/edit',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedPropertiesPropertyIdEditRoute =
  AuthedPropertiesPropertyIdEditRouteImport.update({
    id: '/properties/$propertyId/edit',
    path: '/properties/$propertyId/edit',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedClientsClientIdEditRoute =
  AuthedClientsClientIdEditRouteImport.update({
    id: '/clients/$clientId/edit',
    path: '/clients/$clientId/edit',
    getParentRoute: () => AuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/schedule': typeof AuthedScheduleRoute
  '/clients/new': typeof AuthedClientsNewRoute
  '/invoices/$invoiceId': typeof AuthedInvoicesInvoiceIdRoute
  '/invoices/new': typeof AuthedInvoicesNewRoute
  '/jobs/$jobId': typeof AuthedJobsJobIdRoute
  '/jobs/new': typeof AuthedJobsNewRoute
  '/properties/new': typeof AuthedPropertiesNewRoute
  '/schedules/new': typeof AuthedSchedulesNewRoute
  '/settings/services': typeof AuthedSettingsServicesRoute
  '/clients/': typeof AuthedClientsIndexRoute
  '/money/': typeof AuthedMoneyIndexRoute
  '/settings/': typeof AuthedSettingsIndexRoute
  '/clients/$clientId/edit': typeof AuthedClientsClientIdEditRoute
  '/properties/$propertyId/edit': typeof AuthedPropertiesPropertyIdEditRoute
  '/schedules/$scheduleId/edit': typeof AuthedSchedulesScheduleIdEditRoute
  '/clients/$clientId/': typeof AuthedClientsClientIdIndexRoute
  '/properties/$propertyId/': typeof AuthedPropertiesPropertyIdIndexRoute
}
export interface FileRoutesByTo {
  '/schedule': typeof AuthedScheduleRoute
  '/': typeof AuthedIndexRoute
  '/clients/new': typeof AuthedClientsNewRoute
  '/invoices/$invoiceId': typeof AuthedInvoicesInvoiceIdRoute
  '/invoices/new': typeof AuthedInvoicesNewRoute
  '/jobs/$jobId': typeof AuthedJobsJobIdRoute
  '/jobs/new': typeof AuthedJobsNewRoute
  '/properties/new': typeof AuthedPropertiesNewRoute
  '/schedules/new': typeof AuthedSchedulesNewRoute
  '/settings/services': typeof AuthedSettingsServicesRoute
  '/clients': typeof AuthedClientsIndexRoute
  '/money': typeof AuthedMoneyIndexRoute
  '/settings': typeof AuthedSettingsIndexRoute
  '/clients/$clientId/edit': typeof AuthedClientsClientIdEditRoute
  '/properties/$propertyId/edit': typeof AuthedPropertiesPropertyIdEditRoute
  '/schedules/$scheduleId/edit': typeof AuthedSchedulesScheduleIdEditRoute
  '/clients/$clientId': typeof AuthedClientsClientIdIndexRoute
  '/properties/$propertyId': typeof AuthedPropertiesPropertyIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/_authed/schedule': typeof AuthedScheduleRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/clients/new': typeof AuthedClientsNewRoute
  '/_authed/invoices/$invoiceId': typeof AuthedInvoicesInvoiceIdRoute
  '/_authed/invoices/new': typeof AuthedInvoicesNewRoute
  '/_authed/jobs/$jobId': typeof AuthedJobsJobIdRoute
  '/_authed/jobs/new': typeof AuthedJobsNewRoute
  '/_authed/properties/new': typeof AuthedPropertiesNewRoute
  '/_authed/schedules/new': typeof AuthedSchedulesNewRoute
  '/_authed/settings/services': typeof AuthedSettingsServicesRoute
  '/_authed/clients/': typeof AuthedClientsIndexRoute
  '/_authed/money/': typeof AuthedMoneyIndexRoute
  '/_authed/settings/': typeof AuthedSettingsIndexRoute
  '/_authed/clients/$clientId/edit': typeof AuthedClientsClientIdEditRoute
  '/_authed/properties/$propertyId/edit': typeof AuthedPropertiesPropertyIdEditRoute
  '/_authed/schedules/$scheduleId/edit': typeof AuthedSchedulesScheduleIdEditRoute
  '/_authed/clients/$clientId/': typeof AuthedClientsClientIdIndexRoute
  '/_authed/properties/$propertyId/': typeof AuthedPropertiesPropertyIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/schedule'
    | '/clients/new'
    | '/invoices/$invoiceId'
    | '/invoices/new'
    | '/jobs/$jobId'
    | '/jobs/new'
    | '/properties/new'
    | '/schedules/new'
    | '/settings/services'
    | '/clients/'
    | '/money/'
    | '/settings/'
    | '/clients/$clientId/edit'
    | '/properties/$propertyId/edit'
    | '/schedules/$scheduleId/edit'
    | '/clients/$clientId/'
    | '/properties/$propertyId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/schedule'
    | '/'
    | '/clients/new'
    | '/invoices/$invoiceId'
    | '/invoices/new'
    | '/jobs/$jobId'
    | '/jobs/new'
    | '/properties/new'
    | '/schedules/new'
    | '/settings/services'
    | '/clients'
    | '/money'
    | '/settings'
    | '/clients/$clientId/edit'
    | '/properties/$propertyId/edit'
    | '/schedules/$scheduleId/edit'
    | '/clients/$clientId'
    | '/properties/$propertyId'
  id:
    | '__root__'
    | '/_authed'
    | '/_authed/schedule'
    | '/_authed/'
    | '/_authed/clients/new'
    | '/_authed/invoices/$invoiceId'
    | '/_authed/invoices/new'
    | '/_authed/jobs/$jobId'
    | '/_authed/jobs/new'
    | '/_authed/properties/new'
    | '/_authed/schedules/new'
    | '/_authed/settings/services'
    | '/_authed/clients/'
    | '/_authed/money/'
    | '/_authed/settings/'
    | '/_authed/clients/$clientId/edit'
    | '/_authed/properties/$propertyId/edit'
    | '/_authed/schedules/$scheduleId/edit'
    | '/_authed/clients/$clientId/'
    | '/_authed/properties/$propertyId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/schedule': {
      id: '/_authed/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AuthedScheduleRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/': {
      id: '/_authed/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthedSettingsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/money/': {
      id: '/_authed/money/'
      path: '/money'
      fullPath: '/money/'
      preLoaderRoute: typeof AuthedMoneyIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/clients/': {
      id: '/_authed/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AuthedClientsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/services': {
      id: '/_authed/settings/services'
      path: '/settings/services'
      fullPath: '/settings/services'
      preLoaderRoute: typeof AuthedSettingsServicesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/schedules/new': {
      id: '/_authed/schedules/new'
      path: '/schedules/new'
      fullPath: '/schedules/new'
      preLoaderRoute: typeof AuthedSchedulesNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/properties/new': {
      id: '/_authed/properties/new'
      path: '/properties/new'
      fullPath: '/properties/new'
      preLoaderRoute: typeof AuthedPropertiesNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/jobs/new': {
      id: '/_authed/jobs/new'
      path: '/jobs/new'
      fullPath: '/jobs/new'
      preLoaderRoute: typeof AuthedJobsNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/jobs/$jobId': {
      id: '/_authed/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof AuthedJobsJobIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/invoices/new': {
      id: '/_authed/invoices/new'
      path: '/invoices/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof AuthedInvoicesNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/invoices/$invoiceId': {
      id: '/_authed/invoices/$invoiceId'
      path: '/invoices/$invoiceId'
      fullPath: '/invoices/$invoiceId'
      preLoaderRoute: typeof AuthedInvoicesInvoiceIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/clients/new': {
      id: '/_authed/clients/new'
      path: '/clients/new'
      fullPath: '/clients/new'
      preLoaderRoute: typeof AuthedClientsNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/properties/$propertyId/': {
      id: '/_authed/properties/$propertyId/'
      path: '/properties/$propertyId'
      fullPath: '/properties/$propertyId/'
      preLoaderRoute: typeof AuthedPropertiesPropertyIdIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/clients/$clientId/': {
      id: '/_authed/clients/$clientId/'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId/'
      preLoaderRoute: typeof AuthedClientsClientIdIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/schedules/$scheduleId/edit': {
      id: '/_authed/schedules/$scheduleId/edit'
      path: '/schedules/$scheduleId/edit'
      fullPath: '/schedules/$scheduleId/edit'
      preLoaderRoute: typeof AuthedSchedulesScheduleIdEditRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/properties/$propertyId/edit': {
      id: '/_authed/properties/$propertyId/edit'
      path: '/properties/$propertyId/edit'
      fullPath: '/properties/$propertyId/edit'
      preLoaderRoute: typeof AuthedPropertiesPropertyIdEditRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/clients/$clientId/edit': {
      id: '/_authed/clients/$clientId/edit'
      path: '/clients/$clientId/edit'
      fullPath: '/clients/$clientId/edit'
      preLoaderRoute: typeof AuthedClientsClientIdEditRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedScheduleRoute: typeof AuthedScheduleRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedClientsNewRoute: typeof AuthedClientsNewRoute
  AuthedInvoicesInvoiceIdRoute: typeof AuthedInvoicesInvoiceIdRoute
  AuthedInvoicesNewRoute: typeof AuthedInvoicesNewRoute
  AuthedJobsJobIdRoute: typeof AuthedJobsJobIdRoute
  AuthedJobsNewRoute: typeof AuthedJobsNewRoute
  AuthedPropertiesNewRoute: typeof AuthedPropertiesNewRoute
  AuthedSchedulesNewRoute: typeof AuthedSchedulesNewRoute
  AuthedSettingsServicesRoute: typeof AuthedSettingsServicesRoute
  AuthedClientsIndexRoute: typeof AuthedClientsIndexRoute
  AuthedMoneyIndexRoute: typeof AuthedMoneyIndexRoute
  AuthedSettingsIndexRoute: typeof AuthedSettingsIndexRoute
  AuthedClientsClientIdEditRoute: typeof AuthedClientsClientIdEditRoute
  AuthedPropertiesPropertyIdEditRoute: typeof AuthedPropertiesPropertyIdEditRoute
  AuthedSchedulesScheduleIdEditRoute: typeof AuthedSchedulesScheduleIdEditRoute
  AuthedClientsClientIdIndexRoute: typeof AuthedClientsClientIdIndexRoute
  AuthedPropertiesPropertyIdIndexRoute: typeof AuthedPropertiesPropertyIdIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedScheduleRoute: AuthedScheduleRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedClientsNewRoute: AuthedClientsNewRoute,
  AuthedInvoicesInvoiceIdRoute: AuthedInvoicesInvoiceIdRoute,
  AuthedInvoicesNewRoute: AuthedInvoicesNewRoute,
  AuthedJobsJobIdRoute: AuthedJobsJobIdRoute,
  AuthedJobsNewRoute: AuthedJobsNewRoute,
  AuthedPropertiesNewRoute: AuthedPropertiesNewRoute,
  AuthedSchedulesNewRoute: AuthedSchedulesNewRoute,
  AuthedSettingsServicesRoute: AuthedSettingsServicesRoute,
  AuthedClientsIndexRoute: AuthedClientsIndexRoute,
  AuthedMoneyIndexRoute: AuthedMoneyIndexRoute,
  AuthedSettingsIndexRoute: AuthedSettingsIndexRoute,
  AuthedClientsClientIdEditRoute: AuthedClientsClientIdEditRoute,
  AuthedPropertiesPropertyIdEditRoute: AuthedPropertiesPropertyIdEditRoute,
  AuthedSchedulesScheduleIdEditRoute: AuthedSchedulesScheduleIdEditRoute,
  AuthedClientsClientIdIndexRoute: AuthedClientsClientIdIndexRoute,
  AuthedPropertiesPropertyIdIndexRoute: AuthedPropertiesPropertyIdIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
