/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedScheduleRouteImport } from './routes/_authed/schedule'
import { Route as AuthedPipelineRouteImport } from './routes/_authed/pipeline'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedBoardRouteImport } from './routes/_authed/board'
import { Route as AuthedToolsIndexRouteImport } from './routes/_authed/tools/index'
import { Route as AuthedSettingsIndexRouteImport } from './routes/_authed/settings/index'
import { Route as AuthedMoneyIndexRouteImport } from './routes/_authed/money/index'
import { Route as AuthedInventoryIndexRouteImport } from './routes/_authed/inventory/index'
import { Route as AuthedClientsIndexRouteImport } from './routes/_authed/clients/index'
import { Route as AuthedToolsMulchRouteImport } from './routes/_authed/tools/mulch'
import { Route as AuthedToolsGradeRouteImport } from './routes/_authed/tools/grade'
import { Route as AuthedSettingsSyncRouteImport } from './routes/_authed/settings/sync'
import { Route as AuthedSettingsServicesRouteImport } from './routes/_authed/settings/services'
import { Route as AuthedSettingsProfileRouteImport } from './routes/_authed/settings/profile'
import { Route as AuthedSettingsPreferencesRouteImport } from './routes/_authed/settings/preferences'
import { Route as AuthedSettingsPaymentsRouteImport } from './routes/_authed/settings/payments'
import { Route as AuthedSettingsExportRouteImport } from './routes/_authed/settings/export'
import { Route as AuthedSchedulesNewRouteImport } from './routes/_authed/schedules/new'
import { Route as AuthedPropertiesNewRouteImport } from './routes/_authed/properties/new'
import { Route as AuthedJobsNewRouteImport } from './routes/_authed/jobs/new'
import { Route as AuthedJobsJobIdRouteImport } from './routes/_authed/jobs/$jobId'
import { Route as AuthedInvoicesNewRouteImport } from './routes/_authed/invoices/new'
import { Route as AuthedInvoicesInvoiceIdRouteImport } from './routes/_authed/invoices/$invoiceId'
import { Route as AuthedEstimatesNewRouteImport } from './routes/_authed/estimates/new'
import { Route as AuthedEstimatesEstimateIdRouteImport } from './routes/_authed/estimates/$estimateId'
import { Route as AuthedClientsNewRouteImport } from './routes/_authed/clients/new'
import { Route as AuthedPropertiesPropertyIdIndexRouteImport } from './routes/_authed/properties/$propertyId.index'
import { Route as AuthedClientsClientIdIndexRouteImport } from './routes/_authed/clients/$clientId.index'
import { Route as AuthedSchedulesScheduleIdEditRouteImport } from './routes/_authed/schedules/$scheduleId.edit'
import { Route as AuthedPropertiesPropertyIdEditRouteImport } from './routes/_authed/properties/$propertyId.edit'
import { Route as AuthedClientsClientIdEditRouteImport } from './routes/_authed/clients/$clientId.edit'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedScheduleRoute = AuthedScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPipelineRoute = AuthedPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBoardRoute = AuthedBoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedToolsIndexRoute = AuthedToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsIndexRoute = AuthedSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMoneyIndexRoute = AuthedMoneyIndexRouteImport.update({
  id: '/money/',
  path: '/money/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedInventoryIndexRoute = AuthedInventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedClientsIndexRoute = AuthedClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedToolsMulchRoute = AuthedToolsMulchRouteImport.update({
  id: '/tools/mulch',
  path: '/tools/mulch',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedToolsGradeRoute = AuthedToolsGradeRouteImport.update({
  id: '/tools/grade',
  path: '/tools/grade',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsSyncRoute = AuthedSettingsSyncRouteImport.update({
  id: '/settings/sync',
  path: '/settings/sync',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsServicesRoute = AuthedSettingsServicesRouteImport.update({
  id: '/settings/services',
  path: '/settings/services',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsProfileRoute = AuthedSettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsPreferencesRoute =
  AuthedSettingsPreferencesRouteImport.update({
    id: '/settings/preferences',
    path: '/settings/preferences',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedSettingsPaymentsRoute = AuthedSettingsPaymentsRouteImport.update({
  id: '/settings/payments',
  path: '/settings/payments',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsExportRoute = AuthedSettingsExportRouteImport.update({
  id: '/settings/export',
  path: '/settings/export',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSchedulesNewRoute = AuthedSchedulesNewRouteImport.update({
  id: '/schedules/new',
  path: '/schedules/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPropertiesNewRoute = AuthedPropertiesNewRouteImport.update({
  id: '/properties/new',
  path: '/properties/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedJobsNewRoute = AuthedJobsNewRouteImport.update({
  id: '/jobs/new',
  path: '/jobs/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedJobsJobIdRoute = AuthedJobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedInvoicesNewRoute = AuthedInvoicesNewRouteImport.update({
  id: '/invoices/new',
  path: '/invoices/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedInvoicesInvoiceIdRoute = AuthedInvoicesInvoiceIdRouteImport.update({
  id: '/invoices/$invoiceId',
  path: '/invoices/$invoiceId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedEstimatesNewRoute = AuthedEstimatesNewRouteImport.update({
  id: '/estimates/new',
  path: '/estimates/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedEstimatesEstimateIdRoute =
  AuthedEstimatesEstimateIdRouteImport.update({
    id: '/estimates/$estimateId',
    path: '/estimates/$estimateId',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedClientsNewRoute = AuthedClientsNewRouteImport.update({
  id: '/clients/new',
  path: '/clients/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPropertiesPropertyIdIndexRoute =
  AuthedPropertiesPropertyIdIndexRouteImport.update({
    id: '/properties/$propertyId/',
    path: '/properties/$propertyId/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedClientsClientIdIndexRoute =
  AuthedClientsClientIdIndexRouteImport.update({
    id: '/clients/$clientId/',
    path: '/clients/$clientId/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedSchedulesScheduleIdEditRoute =
  AuthedSchedulesScheduleIdEditRouteImport.update({
    id: '/schedules/$scheduleId/edit',
    path: '/schedules/$scheduleId/edit',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedPropertiesPropertyIdEditRoute =
  AuthedPropertiesPropertyIdEditRouteImport.update({
    id: '/properties/$propertyId/edit',
    path: '/properties/$propertyId/edit',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedClientsClientIdEditRoute =
  AuthedClientsClientIdEditRouteImport.update({
    id: '/clients/$clientId/edit',
    path: '/clients/$clientId/edit',
    getParentRoute: () => AuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/billing': typeof BillingRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/board': typeof AuthedBoardRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/pipeline': typeof AuthedPipelineRoute
  '/schedule': typeof AuthedScheduleRoute
  '/clients/new': typeof AuthedClientsNewRoute
  '/estimates/$estimateId': typeof AuthedEstimatesEstimateIdRoute
  '/estimates/new': typeof AuthedEstimatesNewRoute
  '/invoices/$invoiceId': typeof AuthedInvoicesInvoiceIdRoute
  '/invoices/new': typeof AuthedInvoicesNewRoute
  '/jobs/$jobId': typeof AuthedJobsJobIdRoute
  '/jobs/new': typeof AuthedJobsNewRoute
  '/properties/new': typeof AuthedPropertiesNewRoute
  '/schedules/new': typeof AuthedSchedulesNewRoute
  '/settings/export': typeof AuthedSettingsExportRoute
  '/settings/payments': typeof AuthedSettingsPaymentsRoute
  '/settings/preferences': typeof AuthedSettingsPreferencesRoute
  '/settings/profile': typeof AuthedSettingsProfileRoute
  '/settings/services': typeof AuthedSettingsServicesRoute
  '/settings/sync': typeof AuthedSettingsSyncRoute
  '/tools/grade': typeof AuthedToolsGradeRoute
  '/tools/mulch': typeof AuthedToolsMulchRoute
  '/clients/': typeof AuthedClientsIndexRoute
  '/inventory/': typeof AuthedInventoryIndexRoute
  '/money/': typeof AuthedMoneyIndexRoute
  '/settings/': typeof AuthedSettingsIndexRoute
  '/tools/': typeof AuthedToolsIndexRoute
  '/clients/$clientId/edit': typeof AuthedClientsClientIdEditRoute
  '/properties/$propertyId/edit': typeof AuthedPropertiesPropertyIdEditRoute
  '/schedules/$scheduleId/edit': typeof AuthedSchedulesScheduleIdEditRoute
  '/clients/$clientId/': typeof AuthedClientsClientIdIndexRoute
  '/properties/$propertyId/': typeof AuthedPropertiesPropertyIdIndexRoute
}
export interface FileRoutesByTo {
  '/billing': typeof BillingRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/board': typeof AuthedBoardRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/pipeline': typeof AuthedPipelineRoute
  '/schedule': typeof AuthedScheduleRoute
  '/': typeof AuthedIndexRoute
  '/clients/new': typeof AuthedClientsNewRoute
  '/estimates/$estimateId': typeof AuthedEstimatesEstimateIdRoute
  '/estimates/new': typeof AuthedEstimatesNewRoute
  '/invoices/$invoiceId': typeof AuthedInvoicesInvoiceIdRoute
  '/invoices/new': typeof AuthedInvoicesNewRoute
  '/jobs/$jobId': typeof AuthedJobsJobIdRoute
  '/jobs/new': typeof AuthedJobsNewRoute
  '/properties/new': typeof AuthedPropertiesNewRoute
  '/schedules/new': typeof AuthedSchedulesNewRoute
  '/settings/export': typeof AuthedSettingsExportRoute
  '/settings/payments': typeof AuthedSettingsPaymentsRoute
  '/settings/preferences': typeof AuthedSettingsPreferencesRoute
  '/settings/profile': typeof AuthedSettingsProfileRoute
  '/settings/services': typeof AuthedSettingsServicesRoute
  '/settings/sync': typeof AuthedSettingsSyncRoute
  '/tools/grade': typeof AuthedToolsGradeRoute
  '/tools/mulch': typeof AuthedToolsMulchRoute
  '/clients': typeof AuthedClientsIndexRoute
  '/inventory': typeof AuthedInventoryIndexRoute
  '/money': typeof AuthedMoneyIndexRoute
  '/settings': typeof AuthedSettingsIndexRoute
  '/tools': typeof AuthedToolsIndexRoute
  '/clients/$clientId/edit': typeof AuthedClientsClientIdEditRoute
  '/properties/$propertyId/edit': typeof AuthedPropertiesPropertyIdEditRoute
  '/schedules/$scheduleId/edit': typeof AuthedSchedulesScheduleIdEditRoute
  '/clients/$clientId': typeof AuthedClientsClientIdIndexRoute
  '/properties/$propertyId': typeof AuthedPropertiesPropertyIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/billing': typeof BillingRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/_authed/board': typeof AuthedBoardRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/pipeline': typeof AuthedPipelineRoute
  '/_authed/schedule': typeof AuthedScheduleRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/clients/new': typeof AuthedClientsNewRoute
  '/_authed/estimates/$estimateId': typeof AuthedEstimatesEstimateIdRoute
  '/_authed/estimates/new': typeof AuthedEstimatesNewRoute
  '/_authed/invoices/$invoiceId': typeof AuthedInvoicesInvoiceIdRoute
  '/_authed/invoices/new': typeof AuthedInvoicesNewRoute
  '/_authed/jobs/$jobId': typeof AuthedJobsJobIdRoute
  '/_authed/jobs/new': typeof AuthedJobsNewRoute
  '/_authed/properties/new': typeof AuthedPropertiesNewRoute
  '/_authed/schedules/new': typeof AuthedSchedulesNewRoute
  '/_authed/settings/export': typeof AuthedSettingsExportRoute
  '/_authed/settings/payments': typeof AuthedSettingsPaymentsRoute
  '/_authed/settings/preferences': typeof AuthedSettingsPreferencesRoute
  '/_authed/settings/profile': typeof AuthedSettingsProfileRoute
  '/_authed/settings/services': typeof AuthedSettingsServicesRoute
  '/_authed/settings/sync': typeof AuthedSettingsSyncRoute
  '/_authed/tools/grade': typeof AuthedToolsGradeRoute
  '/_authed/tools/mulch': typeof AuthedToolsMulchRoute
  '/_authed/clients/': typeof AuthedClientsIndexRoute
  '/_authed/inventory/': typeof AuthedInventoryIndexRoute
  '/_authed/money/': typeof AuthedMoneyIndexRoute
  '/_authed/settings/': typeof AuthedSettingsIndexRoute
  '/_authed/tools/': typeof AuthedToolsIndexRoute
  '/_authed/clients/$clientId/edit': typeof AuthedClientsClientIdEditRoute
  '/_authed/properties/$propertyId/edit': typeof AuthedPropertiesPropertyIdEditRoute
  '/_authed/schedules/$scheduleId/edit': typeof AuthedSchedulesScheduleIdEditRoute
  '/_authed/clients/$clientId/': typeof AuthedClientsClientIdIndexRoute
  '/_authed/properties/$propertyId/': typeof AuthedPropertiesPropertyIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/billing'
    | '/login'
    | '/onboarding'
    | '/board'
    | '/dashboard'
    | '/pipeline'
    | '/schedule'
    | '/clients/new'
    | '/estimates/$estimateId'
    | '/estimates/new'
    | '/invoices/$invoiceId'
    | '/invoices/new'
    | '/jobs/$jobId'
    | '/jobs/new'
    | '/properties/new'
    | '/schedules/new'
    | '/settings/export'
    | '/settings/payments'
    | '/settings/preferences'
    | '/settings/profile'
    | '/settings/services'
    | '/settings/sync'
    | '/tools/grade'
    | '/tools/mulch'
    | '/clients/'
    | '/inventory/'
    | '/money/'
    | '/settings/'
    | '/tools/'
    | '/clients/$clientId/edit'
    | '/properties/$propertyId/edit'
    | '/schedules/$scheduleId/edit'
    | '/clients/$clientId/'
    | '/properties/$propertyId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/billing'
    | '/login'
    | '/onboarding'
    | '/board'
    | '/dashboard'
    | '/pipeline'
    | '/schedule'
    | '/'
    | '/clients/new'
    | '/estimates/$estimateId'
    | '/estimates/new'
    | '/invoices/$invoiceId'
    | '/invoices/new'
    | '/jobs/$jobId'
    | '/jobs/new'
    | '/properties/new'
    | '/schedules/new'
    | '/settings/export'
    | '/settings/payments'
    | '/settings/preferences'
    | '/settings/profile'
    | '/settings/services'
    | '/settings/sync'
    | '/tools/grade'
    | '/tools/mulch'
    | '/clients'
    | '/inventory'
    | '/money'
    | '/settings'
    | '/tools'
    | '/clients/$clientId/edit'
    | '/properties/$propertyId/edit'
    | '/schedules/$scheduleId/edit'
    | '/clients/$clientId'
    | '/properties/$propertyId'
  id:
    | '__root__'
    | '/_authed'
    | '/billing'
    | '/login'
    | '/onboarding'
    | '/_authed/board'
    | '/_authed/dashboard'
    | '/_authed/pipeline'
    | '/_authed/schedule'
    | '/_authed/'
    | '/_authed/clients/new'
    | '/_authed/estimates/$estimateId'
    | '/_authed/estimates/new'
    | '/_authed/invoices/$invoiceId'
    | '/_authed/invoices/new'
    | '/_authed/jobs/$jobId'
    | '/_authed/jobs/new'
    | '/_authed/properties/new'
    | '/_authed/schedules/new'
    | '/_authed/settings/export'
    | '/_authed/settings/payments'
    | '/_authed/settings/preferences'
    | '/_authed/settings/profile'
    | '/_authed/settings/services'
    | '/_authed/settings/sync'
    | '/_authed/tools/grade'
    | '/_authed/tools/mulch'
    | '/_authed/clients/'
    | '/_authed/inventory/'
    | '/_authed/money/'
    | '/_authed/settings/'
    | '/_authed/tools/'
    | '/_authed/clients/$clientId/edit'
    | '/_authed/properties/$propertyId/edit'
    | '/_authed/schedules/$scheduleId/edit'
    | '/_authed/clients/$clientId/'
    | '/_authed/properties/$propertyId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  BillingRoute: typeof BillingRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/schedule': {
      id: '/_authed/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AuthedScheduleRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/pipeline': {
      id: '/_authed/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AuthedPipelineRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/board': {
      id: '/_authed/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof AuthedBoardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/tools/': {
      id: '/_authed/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof AuthedToolsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/': {
      id: '/_authed/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthedSettingsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/money/': {
      id: '/_authed/money/'
      path: '/money'
      fullPath: '/money/'
      preLoaderRoute: typeof AuthedMoneyIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/inventory/': {
      id: '/_authed/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof AuthedInventoryIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/clients/': {
      id: '/_authed/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AuthedClientsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/tools/mulch': {
      id: '/_authed/tools/mulch'
      path: '/tools/mulch'
      fullPath: '/tools/mulch'
      preLoaderRoute: typeof AuthedToolsMulchRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/tools/grade': {
      id: '/_authed/tools/grade'
      path: '/tools/grade'
      fullPath: '/tools/grade'
      preLoaderRoute: typeof AuthedToolsGradeRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/sync': {
      id: '/_authed/settings/sync'
      path: '/settings/sync'
      fullPath: '/settings/sync'
      preLoaderRoute: typeof AuthedSettingsSyncRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/services': {
      id: '/_authed/settings/services'
      path: '/settings/services'
      fullPath: '/settings/services'
      preLoaderRoute: typeof AuthedSettingsServicesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/profile': {
      id: '/_authed/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthedSettingsProfileRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/preferences': {
      id: '/_authed/settings/preferences'
      path: '/settings/preferences'
      fullPath: '/settings/preferences'
      preLoaderRoute: typeof AuthedSettingsPreferencesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/payments': {
      id: '/_authed/settings/payments'
      path: '/settings/payments'
      fullPath: '/settings/payments'
      preLoaderRoute: typeof AuthedSettingsPaymentsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/export': {
      id: '/_authed/settings/export'
      path: '/settings/export'
      fullPath: '/settings/export'
      preLoaderRoute: typeof AuthedSettingsExportRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/schedules/new': {
      id: '/_authed/schedules/new'
      path: '/schedules/new'
      fullPath: '/schedules/new'
      preLoaderRoute: typeof AuthedSchedulesNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/properties/new': {
      id: '/_authed/properties/new'
      path: '/properties/new'
      fullPath: '/properties/new'
      preLoaderRoute: typeof AuthedPropertiesNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/jobs/new': {
      id: '/_authed/jobs/new'
      path: '/jobs/new'
      fullPath: '/jobs/new'
      preLoaderRoute: typeof AuthedJobsNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/jobs/$jobId': {
      id: '/_authed/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof AuthedJobsJobIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/invoices/new': {
      id: '/_authed/invoices/new'
      path: '/invoices/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof AuthedInvoicesNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/invoices/$invoiceId': {
      id: '/_authed/invoices/$invoiceId'
      path: '/invoices/$invoiceId'
      fullPath: '/invoices/$invoiceId'
      preLoaderRoute: typeof AuthedInvoicesInvoiceIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/estimates/new': {
      id: '/_authed/estimates/new'
      path: '/estimates/new'
      fullPath: '/estimates/new'
      preLoaderRoute: typeof AuthedEstimatesNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/estimates/$estimateId': {
      id: '/_authed/estimates/$estimateId'
      path: '/estimates/$estimateId'
      fullPath: '/estimates/$estimateId'
      preLoaderRoute: typeof AuthedEstimatesEstimateIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/clients/new': {
      id: '/_authed/clients/new'
      path: '/clients/new'
      fullPath: '/clients/new'
      preLoaderRoute: typeof AuthedClientsNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/properties/$propertyId/': {
      id: '/_authed/properties/$propertyId/'
      path: '/properties/$propertyId'
      fullPath: '/properties/$propertyId/'
      preLoaderRoute: typeof AuthedPropertiesPropertyIdIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/clients/$clientId/': {
      id: '/_authed/clients/$clientId/'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId/'
      preLoaderRoute: typeof AuthedClientsClientIdIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/schedules/$scheduleId/edit': {
      id: '/_authed/schedules/$scheduleId/edit'
      path: '/schedules/$scheduleId/edit'
      fullPath: '/schedules/$scheduleId/edit'
      preLoaderRoute: typeof AuthedSchedulesScheduleIdEditRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/properties/$propertyId/edit': {
      id: '/_authed/properties/$propertyId/edit'
      path: '/properties/$propertyId/edit'
      fullPath: '/properties/$propertyId/edit'
      preLoaderRoute: typeof AuthedPropertiesPropertyIdEditRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/clients/$clientId/edit': {
      id: '/_authed/clients/$clientId/edit'
      path: '/clients/$clientId/edit'
      fullPath: '/clients/$clientId/edit'
      preLoaderRoute: typeof AuthedClientsClientIdEditRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedBoardRoute: typeof AuthedBoardRoute
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedPipelineRoute: typeof AuthedPipelineRoute
  AuthedScheduleRoute: typeof AuthedScheduleRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedClientsNewRoute: typeof AuthedClientsNewRoute
  AuthedEstimatesEstimateIdRoute: typeof AuthedEstimatesEstimateIdRoute
  AuthedEstimatesNewRoute: typeof AuthedEstimatesNewRoute
  AuthedInvoicesInvoiceIdRoute: typeof AuthedInvoicesInvoiceIdRoute
  AuthedInvoicesNewRoute: typeof AuthedInvoicesNewRoute
  AuthedJobsJobIdRoute: typeof AuthedJobsJobIdRoute
  AuthedJobsNewRoute: typeof AuthedJobsNewRoute
  AuthedPropertiesNewRoute: typeof AuthedPropertiesNewRoute
  AuthedSchedulesNewRoute: typeof AuthedSchedulesNewRoute
  AuthedSettingsExportRoute: typeof AuthedSettingsExportRoute
  AuthedSettingsPaymentsRoute: typeof AuthedSettingsPaymentsRoute
  AuthedSettingsPreferencesRoute: typeof AuthedSettingsPreferencesRoute
  AuthedSettingsProfileRoute: typeof AuthedSettingsProfileRoute
  AuthedSettingsServicesRoute: typeof AuthedSettingsServicesRoute
  AuthedSettingsSyncRoute: typeof AuthedSettingsSyncRoute
  AuthedToolsGradeRoute: typeof AuthedToolsGradeRoute
  AuthedToolsMulchRoute: typeof AuthedToolsMulchRoute
  AuthedClientsIndexRoute: typeof AuthedClientsIndexRoute
  AuthedInventoryIndexRoute: typeof AuthedInventoryIndexRoute
  AuthedMoneyIndexRoute: typeof AuthedMoneyIndexRoute
  AuthedSettingsIndexRoute: typeof AuthedSettingsIndexRoute
  AuthedToolsIndexRoute: typeof AuthedToolsIndexRoute
  AuthedClientsClientIdEditRoute: typeof AuthedClientsClientIdEditRoute
  AuthedPropertiesPropertyIdEditRoute: typeof AuthedPropertiesPropertyIdEditRoute
  AuthedSchedulesScheduleIdEditRoute: typeof AuthedSchedulesScheduleIdEditRoute
  AuthedClientsClientIdIndexRoute: typeof AuthedClientsClientIdIndexRoute
  AuthedPropertiesPropertyIdIndexRoute: typeof AuthedPropertiesPropertyIdIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedBoardRoute: AuthedBoardRoute,
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedPipelineRoute: AuthedPipelineRoute,
  AuthedScheduleRoute: AuthedScheduleRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedClientsNewRoute: AuthedClientsNewRoute,
  AuthedEstimatesEstimateIdRoute: AuthedEstimatesEstimateIdRoute,
  AuthedEstimatesNewRoute: AuthedEstimatesNewRoute,
  AuthedInvoicesInvoiceIdRoute: AuthedInvoicesInvoiceIdRoute,
  AuthedInvoicesNewRoute: AuthedInvoicesNewRoute,
  AuthedJobsJobIdRoute: AuthedJobsJobIdRoute,
  AuthedJobsNewRoute: AuthedJobsNewRoute,
  AuthedPropertiesNewRoute: AuthedPropertiesNewRoute,
  AuthedSchedulesNewRoute: AuthedSchedulesNewRoute,
  AuthedSettingsExportRoute: AuthedSettingsExportRoute,
  AuthedSettingsPaymentsRoute: AuthedSettingsPaymentsRoute,
  AuthedSettingsPreferencesRoute: AuthedSettingsPreferencesRoute,
  AuthedSettingsProfileRoute: AuthedSettingsProfileRoute,
  AuthedSettingsServicesRoute: AuthedSettingsServicesRoute,
  AuthedSettingsSyncRoute: AuthedSettingsSyncRoute,
  AuthedToolsGradeRoute: AuthedToolsGradeRoute,
  AuthedToolsMulchRoute: AuthedToolsMulchRoute,
  AuthedClientsIndexRoute: AuthedClientsIndexRoute,
  AuthedInventoryIndexRoute: AuthedInventoryIndexRoute,
  AuthedMoneyIndexRoute: AuthedMoneyIndexRoute,
  AuthedSettingsIndexRoute: AuthedSettingsIndexRoute,
  AuthedToolsIndexRoute: AuthedToolsIndexRoute,
  AuthedClientsClientIdEditRoute: AuthedClientsClientIdEditRoute,
  AuthedPropertiesPropertyIdEditRoute: AuthedPropertiesPropertyIdEditRoute,
  AuthedSchedulesScheduleIdEditRoute: AuthedSchedulesScheduleIdEditRoute,
  AuthedClientsClientIdIndexRoute: AuthedClientsClientIdIndexRoute,
  AuthedPropertiesPropertyIdIndexRoute: AuthedPropertiesPropertyIdIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  BillingRoute: BillingRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
